# fly.toml file generated for reljr on 2023-04-08T13:58:15-04:00

app = "reljr"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mia"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
